apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    architecture: x86_64
    authoritative-source-url: registry.access.redhat.com
    build-date: 2019-10-24T06:19:47.767716
    commit.image.appsody.dev/author: hollisc <hollisc@ca.ibm.com>
    commit.image.appsody.dev/committer: hollisc <hollisc@ca.ibm.com>
    commit.image.appsody.dev/date: Thu Nov 7 11:29:59 2019 -0500
    commit.image.appsody.dev/message: Update default.json
    description: This image contains the Kabanero development stack for the Nodejs
      collection
    distribution-scope: public
    help: For more information visit https://github.com/sclorg/s2i-nodejs-container
    image.opencontainers.org/created: "2019-11-07T12:20:02-05:00"
    image.opencontainers.org/documentation: https://github.com/hollisc/refarch-cloudnative-bluecompute-web-appsody
    image.opencontainers.org/revision: a9c2e7628aa795c4ab1b3656581ec7cc1ce6e7fa-modified
    image.opencontainers.org/source: https://github.com/hollisc/refarch-cloudnative-bluecompute-web-appsody/tree/master
    image.opencontainers.org/url: https://github.com/hollisc/refarch-cloudnative-bluecompute-web-appsody
    k8s.io/description: Node.js 10 available as container is a base platform for building
      and running various Node.js 10 applications and frameworks. Node.js is a platform
      built on Chrome's JavaScript runtime for easily building fast, scalable network
      applications. Node.js uses an event-driven, non-blocking I/O model that makes
      it lightweight and efficient, perfect for data-intensive real-time applications
      that run across distributed devices.
    k8s.io/display-name: Node.js 10
    maintainer: SoftwareCollections.org <sclorg@redhat.com>
    name: kabanero/nodejs
    openshift.io/expose-services: 8080:http
    openshift.io/tags: builder,nodejs,nodejs10
    redhat.com/build-host: cpt-1008.osbs.prod.upshift.rdu2.redhat.com
    redhat.com/component: nodejs-10-container
    redhat.com/deployments-dir: /opt/app-root/src
    redhat.com/dev-mode: DEV_MODE:false
    redhat.com/dev-mode.port: DEBUG_PORT:5858
    redhat.com/license_terms: https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI
    release: "51.1571897147"
    s2i.io/scripts-url: image:///usr/libexec/s2i
    s2i.openshift.io/scripts-url: image:///usr/libexec/s2i
    stack.appsody.dev/configured: kabanero/nodejs:0.2
    stack.appsody.dev/created: 2019-11-04T16:14:28+0000
    stack.appsody.dev/revision: 4a4125e82be6db5fdde5205105e8bbd8c15c1ee7
    stack.appsody.dev/tag: kabanero/nodejs:0.2.5
    summary: Image for Kabanero Nodejs development
    url: https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/nodejs-10/images/1-51.1571897147
    usage: s2i build <SOURCE-REPOSITORY> ubi8/nodejs-10:latest <APP-NAME>
    vcs-ref: aef149a18b9d2468ff792fe2c76642af20866aec
    vcs-type: git
    vendor: Kabanero
    version: 0.2.5
  labels:
    image.opencontainers.org/title: web
    stack.appsody.dev/version: 0.2.5
  name: web
  namespace: dev
spec:
applicationImage: us.icr.io/devops-gse-poc/refarch-cloudnative-bluecompute-web-appsody:ce7ed4d53e33d724499ccd97cf68ce01c8139377
  createKnativeService: false
  expose: true
  service:
    port: 8000
    targetPort: 8000
    type: ClusterIP
  stack: nodejs
  version: 1.0.0
  pullSecret: ibm-cr-pull-secret
  #serviceAccountName: kabanero-operator
  #replicas: 2




